### ISSUE TITLE
[wifi_iot] WiFi Connection not working on Pixel 6 Android 12

### ISSUE THREAD

**Issue by kbessemer** [flutternetwork/WiFiFlutter#273] opened 2022-04-19 20:09 UTC
So far this plugin has worked on my iPad, and Lenovo Android 11 Tablet. But today I got a Pixel 6 Android 12 for further testing - it is behaving normally, it asks to join the correct network, and Android even shows a notification saying the connection is successful, but it does not actually connect to the network my app is telling it to.

`bool result = await WiFiForIoTPlugin.connect(ssid,
        password: password,
        joinOnce: true,
        security: NetworkSecurity.WPA,);
    if (result) {
      WiFiForIoTPlugin.forceWifiUsage(true);
      Navigator.push(
          context,
          MaterialPageRoute(
              builder: (context) => Login()
          )
      );
    }`

**Comment by kbessemer** [comment] 2022-04-19 20:24
If I manually connect to the WiFi network, then run my app, it works normally. I tried running the app with the WiFi network saved, but disconnected, did not work.

**Comment by daadu** [comment] 2022-04-20 06:21
Can you share logs, could be that the phone does not find the network "good" and would revert to older one - can you retry after forgetting old network?

**Comment by kbessemer** [comment] 2022-04-20 17:58
Ok, so when I forget all wifi networks that are saved, the app with wifi_iot does connect me to the requested network successfully. Do you know of a better fix for this?

**Comment by kbessemer** [comment] 2022-04-20 19:53
I found the disconnect function in wifi_iot but it is not working for me.

Error:
E/WifiIotPlugin(21026): Can't disconnect from WiFi, networkCallback and networkSuggestions is null.

Code:
    var disc = await WiFiForIoTPlugin.disconnect();

**Comment by kbessemer** [comment] 2022-04-21 18:47
Ok, I understand. Is there any way to get this working on Android 12? Only work around I have found is to manually disconnect from my current wifi network before running my app that has wifi_iot

**Comment by daadu** [comment] 2022-04-22 10:46
Need to know the reason why Android is disconnecting, log you shared has no info about it.

**Comment by kbessemer** [comment] 2022-05-03 17:45
I do not see any settings that match this criteria in the phone. There are not many settings under WiFi, there is "Adaptive connectivity" I have tried disabling this with no success

**Comment by kbessemer** [comment] 2022-05-03 17:45
There are also no errors in the console when trying to connect to the WiFi network on the android 12 device

**Comment by kbessemer** [comment] 2022-05-03 20:34
Sorry for 3rd reply, wanted to show you how this is operating on android 12/pixel 6:
http://kylebessemer.com/wifi.mp4

You can see that the WiFi connection shows as successful everytime I try to connect by android popup notification, but it is not actually joining the network. After the 2nd attempt I manually disconnect from my current WiFi network and then attempt to connect using the wifi_iot plugin again and it works that time.

I should add that the hotspot I am trying to connect to does not have internet access, it is an IoT device.

Below is the console log, the line with "address = 192.168.187.241" is from a failed API call to the backend on the IoT device, this is used to confirm connectivity with the device.

Launching lib/main.dart on Pixel 6 in debug mode...
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Debug service listening on ws://127.0.0.1:57055/3GU1Yl0Z-UA=/ws
Syncing files to device Pixel 6...
I/flutter (12680): MS_FeverWarn_b827eb3d791f
I/flutter (12680): MS_FeverWarn_b827eb3d791f
E/flutter (12680): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: SocketException: Software caused connection abort (OS Error: Software caused connection abort, errno = 103), address = 192.168.187.241, port = 35138
E/flutter (12680): #0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:682:35)
E/flutter (12680): #1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1817:26)
E/flutter (12680): #2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
E/flutter (12680): #3      Socket._startConnect (dart:io-patch/socket_patch.dart:2038:22)
E/flutter (12680): #4      Socket.startConnect (dart:io/socket.dart:792:21)
E/flutter (12680): #5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2440:18)
E/flutter (12680): #6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2834:12)
E/flutter (12680): #7      _HttpClient._getConnection (dart:_http/http_impl.dart:2839:12)
E/flutter (12680): #8      _HttpClient._openUrl (dart:_http/http_impl.dart:2698:12)
E/flutter (12680): #9      _HttpClient.openUrl (dart:_http/http_impl.dart:2570:7)
E/flutter (12680): #10     IOClient.send (package:http/src/io_client.dart:35:38)
E/flutter (12680): #11     BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:38)
E/flutter (12680): #12     BaseClient.get (package:http/src/base_client.dart:27:7)
E/flutter (12680): #13     get.<anonymous closure> (package:http/http.dart:46:36)
E/flutter (12680): #14     _withClient (package:http/http.dart:164:20)
E/flutter (12680): #15     get (package:http/http.dart:46:5)
E/flutter (12680): #16     _ConnectState.PingGet (package:flutter_analyzer/components/connect.dart:82:17)
E/flutter (12680): #17     _ConnectState.PingHandler (package:flutter_analyzer/components/connect.dart:92:21)
E/flutter (12680): <asynchronous suspension>
E/flutter (12680): 
E/flutter (12680): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: SocketException: Software caused connection abort (OS Error: Software caused connection abort, errno = 103), address = 192.168.187.241, port = 35140
E/flutter (12680): #0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:682:35)
E/flutter (12680): #1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1817:26)
E/flutter (12680): #2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
E/flutter (12680): #3      Socket._startConnect (dart:io-patch/socket_patch.dart:2038:22)
E/flutter (12680): #4      Socket.startConnect (dart:io/socket.dart:792:21)
E/flutter (12680): #5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2440:18)
E/flutter (12680): #6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2834:12)
E/flutter (12680): #7      _HttpClient._getConnection (dart:_http/http_impl.dart:2839:12)
E/flutter (12680): #8      _HttpClient._openUrl (dart:_http/http_impl.dart:2698:12)
E/flutter (12680): #9      _HttpClient.openUrl (dart:_http/http_impl.dart:2570:7)
E/flutter (12680): #10     IOClient.send (package:http/src/io_client.dart:35:38)
E/flutter (12680): #11     BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:38)
E/flutter (12680): #12     BaseClient.get (package:http/src/base_client.dart:27:7)
E/flutter (12680): #13     get.<anonymous closure> (package:http/http.dart:46:36)
E/flutter (12680): #14     _withClient (package:http/http.dart:164:20)
E/flutter (12680): #15     get (package:http/http.dart:46:5)
E/flutter (12680): #16     _ConnectState.PingGet (package:flutter_analyzer/components/connect.dart:82:17)
E/flutter (12680): #17     _ConnectState.PingHandler (package:flutter_analyzer/components/connect.dart:92:21)
E/flutter (12680): <asynchronous suspension>
E/flutter (12680): 
I/OpenGLRenderer(12680): Davey! duration=79454ms; Flags=1, FrameTimelineVsyncId=23004, IntendedVsync=332622070017, Vsync=332622070017, InputEventId=0, HandleInputStart=332622291950, AnimationStart=332622293130, PerformTraversalsStart=332622293618, DrawStart=332622656859, FrameDeadline=332655336684, FrameInterval=332622285358, FrameStartTime=16666667, SyncQueued=332623080117, SyncStart=332623099893, IssueDrawCommandsStart=332623365070, SwapBuffers=332630632363, FrameCompleted=412076406491, DequeueBufferDuration=813720, QueueBufferDuration=618245, GpuCompleted=412076406491, SwapBuffersCompleted=332631287677, DisplayPresentTime=0, 
I/flutter (12680): MS_FeverWarn_b827eb3d791f
I/OpenGLRenderer(12680): Davey! duration=50742ms; Flags=0, FrameTimelineVsyncId=29223, IntendedVsync=366240170005, Vsync=366240170005, InputEventId=1049296413, HandleInputStart=366240751968, AnimationStart=366240753392, PerformTraversalsStart=366240838272, DrawStart=366248494969, FrameDeadline=366267881116, FrameInterval=366240747492, FrameStartTime=11111111, SyncQueued=366248696751, SyncStart=366248736139, IssueDrawCommandsStart=366248801854, SwapBuffers=366253935195, FrameCompleted=416982897663, DequeueBufferDuration=2401001, QueueBufferDuration=355551, GpuCompleted=416982897663, SwapBuffersCompleted=366254963841, DisplayPresentTime=0,

**Comment by kbessemer** [comment] 2022-05-05 21:07
> Having the same issue

Are you using a Pixel 6 phone? Or is it a different phone model also running Android 12?

**Comment by seikosantana** [comment] 2022-05-06 13:29
it's a different phone, and it's android 10, but i managed to solve it with what's mentioned in https://github.com/flutternetwork/WiFiFlutter/issues/247

From my inspection, yes it successfully made connection, but wasn't able to reach LAN, which is needed in my case, to communicate with the IoT device.
so I do put
```cs
await forceWifiUsage(true);
```
after a successful connection and network traffic to the LAN will then be routed.

**Comment by kbessemer** [comment] 2022-05-06 14:44
Ok, that is not the issue I am facing. I am already using forceWifiUsage. Works perfectly on Android 11 but not 12

**Comment by hanlectin** [comment] 2022-05-16 07:59
I can confirm the very same behavior: works on all configurations I tried, except Pixel 6 and Android 12

**Comment by daadu** [comment] 2022-05-16 08:17
@kbessemer I will test on Android 12, and get back.

**Comment by daadu** [comment] 2022-05-16 08:43
Looks like some APIs are deprecated in SDK 31 (Android 12) - https://developer.android.com/about/versions/12/behavior-changes-12#concurrent-connections


I am working on it, will open a PR when ready with patch - urge all to test against that PR with as many devices as possible (different versions, vendors, etc).

**Comment by daadu** [comment] 2022-05-16 11:51
I am failing to reproduce the issue with Android 12 phone(iQOO 9 SE) with the latest version of `wifi_iot` on pub.dev.

**Comment by daadu** [comment] 2022-05-16 11:54
@kbessemer I have done some implementation changes at #283, can you verify that this fixes the problem (highly unlikely though).

I don't have a Pixel 6 phone to test this against.

**Comment by hanlectin** [comment] 2022-05-16 12:05
sorry, I can't test at the moment.
but I can confirm what I tried yesterday:
* used wifi_scan 0.2.1 (not 0.3.0 yet)
* SSID was WPA secure
* using: await WiFiForIoTPlugin.connect(ssid, password: '12345678', joinOnce: true, security: NetworkSecurity.WPA, withInternet: false);
* returns with "Connected OK" toast (similar text)
* ...but there is no connection target (192.168.4.1)
==> I need to connect to the above SSID in Internet/WiFi  -> then it works!
(last step is NOT necessary on < Android 12). it works right after calling WiFiForIoTPlugin.connect()

**Comment by hanlectin** [comment] 2022-05-16 12:10
I'll test with wifi_scan v0.3.0 and/or android:usesCleartextTraffic="true" later today...

**Comment by seikosantana** [comment] 2022-05-16 13:54
I don't have Android 12 device but i'll try compiling to SDK Level 30

**Comment by hanlectin** [comment] 2022-05-17 07:43
I don't know how to disable "internet requests"?! Lot's of apps installed. Surely many of these try to connect whenever there's a chance ;(
My "wifi_scan" app was until yesterday using flutter 2.10.x. since yesterday 3.0.0: no difference there!
its always 

facts/summarize:
* WiFi connected to IoT device (via system settings), cellular data disabled:
   --> connection OK, (wifi_scan not used/not necessary)
* WiFi connected to IoT device (via system settings), cellular data enabled:
   --> need wifi_scan WiFiForIoTPlugin.forceWifiUsage(true) - otherwise app tries to connect via cellular data
* WiFi connected to internet-connected AP
   --> need wifi_scan WiFiForIoTPlugin.connect() & WiFiForIoTPlugin.forceWifiUsage(true)   
   ==> this works with many/all(?) combinations, but NOT with Android12/Pixel6
   (while WiFiForIoTPlugin is in use and connected to the IoT device, the previous internet-WiFi is not working; however, I think I recently read that with Android 13 it might be possible to keep two (or more) WiFi connections in parallel. on supported hardware. unfortunately I can't find that article at the moment...)

**Comment by daadu** [comment] 2022-05-17 07:51
I have wrapped `forceWifiUsage` around an HTTP client

```dart
class _WifiForcedClient extends http.BaseClient {
  _WifiForcedClient(this._inner);

  final http.Client _inner;

  Future<void> _forceWifiUsage(bool force, {String logTag = ""}) async {
    logTag += ": _forceWifiUsage($force)";

    try {
      print("$logTag: started");
      await WiFiForIoTPlugin.forceWifiUsage(force);
      print("$logTag: done");
    } catch (e, s) {
      print("$logTag: failed $e, $s");
    }
  }

  @override
  Future<http.StreamedResponse> send(http.BaseRequest request) async {
    try {
      //  enable - force wifi usage
      await _forceWifiUsage(true, logTag: "_WifiForcedClient");

      // call send on inner client
      return await _inner.send(request);
    } finally {
      //  disable - force wifi usage
      await _forceWifiUsage(false, logTag: "_WifiForcedClient");
    }
  }
}
```

I use this client to make all HTTP calls via AP connected by my app, rest I use normal app.

I think in your case, you will have to disable `forceWifiUsage` back when you try to make "calls to the internet" - usin g the above client will help you organise traffic properly.

**Comment by daadu** [comment] 2022-05-17 07:56
@hanlectin I meant disabling network calls from your app.

**Comment by daadu** [comment] 2022-05-17 07:58
> I think I recently read that with Android 13 it might be possible to keep two (or more) WiFi connections in parallel. on supported hardware. unfortunately I can't find that article at the moment...)

@hanlectin Android will **support** such multiple connections, but will be left to device vendor to support it at Wifi driver/firmware level.

**Comment by hanlectin** [comment] 2022-05-17 08:12
> @hanlectin I meant disabling network calls from your app.
thanks. sure. understood...
FYI: my application is different: my app connects to a measurement-device that sends data (and can be controlled) via WiFi (it provides a WiFi hotspot). most of the time, this device will come with a dedicated android phone/tablet as a controller. in that case the phone will never need to access the internet at all... (here I can easily configure only one WiFi connection in system-settings and keep it that way)
also sometimes, one phone should operate multiple measurement-devices. so fast switching devices from wihtin the app (using wifi_scan) is a real benefit. and works fine. possible even with Android 12 as there will not be any mobile data enabled on the phone running the app.
during development (and for testing) I sometimes use my own phone (Pixel 6). here I found the problems...
--> however, at the end, the currenly observed Android 12 issues are not a deal-breaker for my purpose, as we won't be using Pixel6/Android12 devices bundled with the mwasurement devices.
It's currently more or less personal interest to also have in running on Pixel6, too - as I don't really see why it shouldn't work here too...
maybe there will be a future need to really have it wokring on a Pixel6/Android12... but for now: not (really) important!

nevertheless: thanks a lot for your efforts!!!
(and please let me know if I can test anything if there's an update available)

**Comment by daadu** [comment] 2022-05-17 08:18
@kbessemer  Some observation,

I got `Software caused connection abort` error, when the IoT device reboots (because of brownout - low power) after connection is made and device tries to make network request.

I can fix these when device is connected to proper power source (5V 2A adapter).

**Comment by daadu** [comment] 2022-05-17 08:22
@hanlectin Sure, will let you know when there is clarity in what is wrong and patch is ready to test against Android 12 device. As of now I am unable to consistently reproduce the issue with Android 12 phone I have - as of now I think this is a non-issue on Android 12 (could be Pixel6 specific thing) - as I obsereved this issue only when my access point where app connected not sufficiently powered.

**Comment by alexs-sentrytechnology** [comment] 2022-06-16 09:55
Hi - I get this issue on my pixel 6 pro running Android 12 also. Seems to be a pixel 6 think - my code runs successfully on other phones.

**Comment by daadu** [comment] 2022-06-19 06:19
Sorry, I don't have Pixel 6 to test. Would encourage once who have it to debug the issue.

**Comment by JohnMaguire** [comment] 2022-09-20 04:59
I stumbled across this issue as I was thinking about an issue I experienced last year, which sounds exactly like this one, including running a Pixel 6 with Android 12. It was disappointing since it sort of rendered my app's value moot for me.

There is also this longstanding issue in the GoPro community... I believe the Pixel 6 has some issue inherent to it: https://community.gopro.com/s/question/0D53b00008GqI88CAF/unable-to-connect-to-gopro-hero-10s-wifi-via-the-quik-app-on-pixel-6-pro-android-12?language=en_US

**Comment by Martichou** [comment] 2022-09-23 12:25
Hey ! I'm not sure if anyone dig a bit deeper in this, but I tried.

(tested on a Pixel 6 with Android 13)
What I discovered is that when you call connect (or findAndConnect, it doesn't matter), the Network object you get have an ID. Let's say that ID is 190. The issue come when you try to forceWifiUsage, the Network object that function use is 183 (number are just pure indication and may varies).

That issue only appears when you are already connected to another Wifi network before calling the connect method. It seems to be due to the fact that since Android 12, a device can be connected to multiple access points.

I've not yet found a correct way to fix this. For the moment my current workaround is to bindProcessToNetwork in the connect function (precisely in the connectTo function). 

Someone have a better idea for a fix ?

**Comment by daadu** [comment] 2022-09-23 12:47
@Martichou Thanks for the efforts.

Currently, we are not doing `forceWifiUsage` with `connect` by default, is because want to give this control to user when to enable or disable this network for communication.

What I suggest is to use `Network` object (if avaible) we get in `onAvailable` directly (will have to make sure that the objects is cleaned up properly if disconnected) inside `connectTo`. Can you try this and see if that issue is resolved. Unfortunately, I dont have any Android 13 or Pixel phone to test this.

**Comment by Martichou** [comment] 2022-09-23 16:09
@daadu I know about the reasoning behind why you don't enforce the forceWifiUsage :).

I've just done as you recommended and it seems to work just fine. I was able to connect and to forceWifiUsage while staying connected to the previous AP. So the Pixel I had was connected to both AP at the same time and the APP was speaking to the one used in connect.

I will try to clean things up and ensure I clean the object correctly and then send a patch for you to review. Maybe we'll get a fix finally! 😉

**Comment by darhaywa** [comment] 2022-11-04 16:57
@Martichou thanks for your solution I've put a PR in place with a tidied-up version.

@daadu could you take a look and let us know if there are any issues?

**Comment by daadu** [comment] 2022-11-05 10:24
@darhaywa Thanks for the PR.

@Martichou  Thanks for working on it.

**Comment by daadu** [comment] 2022-11-05 10:50
This fix has landed on pub.dev with [v0.3.18](https://pub.dev/packages/wifi_iot/versions/0.3.18)

@kbessemer Thank for reporting this. Check yourself [here](https://github.com/flutternetwork/WiFiFlutter/blob/master/CONTRIBUTORS.md)!

Closing this issue. Feel free to ask for re-opening if not resolved.

**Closed by daadu** 2022-11-05 10:50 UTC
Labels: bug
